<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["memberImage", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Create memberImage
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "memberImage/create",
            "autocomplete" => "off",
            "class" => "form-horizontal",
            "enctype" => "multipart/form-data",
        ]
    );
?>

<input type="hidden" name="memberid" value="<?php echo $memberid?>"/>

<div class="form-group">
    <label for="fieldDescription" class="col-sm-2 control-label">Description</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["description[]", "size" => 30, "class" => "form-control", "id" => "fieldDescription[]"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldImageFile" class="col-sm-2 control-label">ImageFile</label>
    <div class="col-sm-10">
        <?php echo $this->tag->fileField(["imageFile[]", "size" => 30, "class" => "form-control", "id" => "fieldImageFile[]"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
